#include "reflection_impl.h"
#include "/usr/include/Qt/qapplication.h"

BEGIN_CLASS(QEventLoop)
SUPER_CLASS(QObject)
STATIC_METHOD(tr, QString, const char *, const char *)
STATIC_METHOD(trUtf8, QString, const char *, const char *)
STATIC_METHOD(tr, QString, const char *, const char *, int)
STATIC_METHOD(trUtf8, QString, const char *, const char *, int)
CONSTRUCTOR(QObject *)
METHOD(processEvents, bool, QFlags<QEventLoop::ProcessEventsFlag>)
METHOD(processEvents, void, QFlags<QEventLoop::ProcessEventsFlag>, int)
METHOD(exec, int, QFlags<QEventLoop::ProcessEventsFlag>)
METHOD(exit, void, int)
CONST_METHOD(isRunning, bool)
METHOD(wakeUp, void)
METHOD(quit, void)
METHOD(operator=, QEventLoop &, const QEventLoop &)
END_CLASS

BEGIN_CLASS(QList<void *>)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(const QList<void *> &)
METHOD(operator=, QList<void *> &, const QList<void *> &)
METHOD(swap, void, QList<void *> &)
CONST_METHOD(operator==, bool, const QList<void *> &)
CONST_METHOD(operator!=, bool, const QList<void *> &)
CONST_METHOD(size, int)
METHOD(detach, void)
METHOD(detachShared, void)
CONST_METHOD(isDetached, bool)
METHOD(setSharable, void, bool)
CONST_METHOD(isSharedWith, bool, const QList<void *> &)
CONST_METHOD(isEmpty, bool)
METHOD(clear, void)
CONST_METHOD(at, void *const &, int)
CONST_METHOD(operator[], void *const &, int)
METHOD(operator[], void *&, int)
METHOD(reserve, void, int)
METHOD(append, void, void *const &)
METHOD(append, void, const QList<void *> &)
METHOD(prepend, void, void *const &)
METHOD(insert, void, int, void *const &)
METHOD(replace, void, int, void *const &)
METHOD(removeAt, void, int)
METHOD(removeAll, int, void *const &)
METHOD(removeOne, bool, void *const &)
METHOD(takeAt, void *, int)
METHOD(takeFirst, void *)
METHOD(takeLast, void *)
METHOD(move, void, int, int)
METHOD(swap, void, int, int)
CONST_METHOD(indexOf, int, void *const &, int)
CONST_METHOD(lastIndexOf, int, void *const &, int)
CONST_METHOD(contains, QBool, void *const &)
CONST_METHOD(count, int, void *const &)
METHOD(begin, QList<void *>::iterator)
CONST_METHOD(begin, QList<void *>::const_iterator)
CONST_METHOD(constBegin, QList<void *>::const_iterator)
METHOD(end, QList<void *>::iterator)
CONST_METHOD(end, QList<void *>::const_iterator)
CONST_METHOD(constEnd, QList<void *>::const_iterator)
METHOD(insert, QList<void *>::iterator, QList<void *>::iterator, void *const &)
METHOD(erase, QList<void *>::iterator, QList<void *>::iterator)
METHOD(erase, QList<void *>::iterator, QList<void *>::iterator, QList<void *>::iterator)
CONST_METHOD(count, int)
CONST_METHOD(length, int)
METHOD(first, void *&)
CONST_METHOD(first, void *const &)
METHOD(last, void *&)
CONST_METHOD(last, void *const &)
METHOD(removeFirst, void)
METHOD(removeLast, void)
CONST_METHOD(startsWith, bool, void *const &)
CONST_METHOD(endsWith, bool, void *const &)
CONST_METHOD(mid, QList<void *>, int, int)
CONST_METHOD(value, void *, int)
CONST_METHOD(value, void *, int, void *const &)
METHOD(push_back, void, void *const &)
METHOD(push_front, void, void *const &)
METHOD(front, void *&)
CONST_METHOD(front, void *const &)
METHOD(back, void *&)
CONST_METHOD(back, void *const &)
METHOD(pop_front, void)
METHOD(pop_back, void)
CONST_METHOD(empty, bool)
METHOD(operator+=, QList<void *> &, const QList<void *> &)
CONST_METHOD(operator+, QList<void *>, const QList<void *> &)
METHOD(operator+=, QList<void *> &, void *const &)
METHOD(operator<<, QList<void *> &, void *const &)
METHOD(operator<<, QList<void *> &, const QList<void *> &)
CONST_METHOD(toVector, QVector<void *>)
CONST_METHOD(toSet, QSet<void *>)
STATIC_METHOD(fromVector, QList<void *>, const QVector<void *> &)
STATIC_METHOD(fromSet, QList<void *>, const QSet<void *> &)
STATIC_METHOD(fromStdList, QList<void *>, const std::list<void *, std::allocator<void *> > &)
END_CLASS

BEGIN_CLASS(QList<QWidget *>)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(const QList<QWidget *> &)
METHOD(operator=, QList<QWidget *> &, const QList<QWidget *> &)
METHOD(swap, void, QList<QWidget *> &)
CONST_METHOD(operator==, bool, const QList<QWidget *> &)
CONST_METHOD(operator!=, bool, const QList<QWidget *> &)
CONST_METHOD(size, int)
METHOD(detach, void)
METHOD(detachShared, void)
CONST_METHOD(isDetached, bool)
METHOD(setSharable, void, bool)
CONST_METHOD(isSharedWith, bool, const QList<QWidget *> &)
CONST_METHOD(isEmpty, bool)
METHOD(clear, void)
CONST_METHOD(at, QWidget *const &, int)
CONST_METHOD(operator[], QWidget *const &, int)
METHOD(operator[], QWidget *&, int)
METHOD(reserve, void, int)
METHOD(append, void, QWidget *const &)
METHOD(append, void, const QList<QWidget *> &)
METHOD(prepend, void, QWidget *const &)
METHOD(insert, void, int, QWidget *const &)
METHOD(replace, void, int, QWidget *const &)
METHOD(removeAt, void, int)
METHOD(removeAll, int, QWidget *const &)
METHOD(removeOne, bool, QWidget *const &)
METHOD(takeAt, QWidget *, int)
METHOD(takeFirst, QWidget *)
METHOD(takeLast, QWidget *)
METHOD(move, void, int, int)
METHOD(swap, void, int, int)
CONST_METHOD(indexOf, int, QWidget *const &, int)
CONST_METHOD(lastIndexOf, int, QWidget *const &, int)
CONST_METHOD(contains, QBool, QWidget *const &)
CONST_METHOD(count, int, QWidget *const &)
METHOD(begin, QList<QWidget *>::iterator)
CONST_METHOD(begin, QList<QWidget *>::const_iterator)
CONST_METHOD(constBegin, QList<QWidget *>::const_iterator)
METHOD(end, QList<QWidget *>::iterator)
CONST_METHOD(end, QList<QWidget *>::const_iterator)
CONST_METHOD(constEnd, QList<QWidget *>::const_iterator)
METHOD(insert, QList<QWidget *>::iterator, QList<QWidget *>::iterator, QWidget *const &)
METHOD(erase, QList<QWidget *>::iterator, QList<QWidget *>::iterator)
METHOD(erase, QList<QWidget *>::iterator, QList<QWidget *>::iterator, QList<QWidget *>::iterator)
CONST_METHOD(count, int)
CONST_METHOD(length, int)
METHOD(first, QWidget *&)
CONST_METHOD(first, QWidget *const &)
METHOD(last, QWidget *&)
CONST_METHOD(last, QWidget *const &)
METHOD(removeFirst, void)
METHOD(removeLast, void)
CONST_METHOD(startsWith, bool, QWidget *const &)
CONST_METHOD(endsWith, bool, QWidget *const &)
CONST_METHOD(mid, QList<QWidget *>, int, int)
CONST_METHOD(value, QWidget *, int)
CONST_METHOD(value, QWidget *, int, QWidget *const &)
METHOD(push_back, void, QWidget *const &)
METHOD(push_front, void, QWidget *const &)
METHOD(front, QWidget *&)
CONST_METHOD(front, QWidget *const &)
METHOD(back, QWidget *&)
CONST_METHOD(back, QWidget *const &)
METHOD(pop_front, void)
METHOD(pop_back, void)
CONST_METHOD(empty, bool)
METHOD(operator+=, QList<QWidget *> &, const QList<QWidget *> &)
CONST_METHOD(operator+, QList<QWidget *>, const QList<QWidget *> &)
METHOD(operator+=, QList<QWidget *> &, QWidget *const &)
METHOD(operator<<, QList<QWidget *> &, QWidget *const &)
METHOD(operator<<, QList<QWidget *> &, const QList<QWidget *> &)
CONST_METHOD(toVector, QVector<QWidget *>)
CONST_METHOD(toSet, QSet<QWidget *>)
STATIC_METHOD(fromVector, QList<QWidget *>, const QVector<QWidget *> &)
STATIC_METHOD(fromSet, QList<QWidget *>, const QSet<QWidget *> &)
STATIC_METHOD(fromStdList, QList<QWidget *>, const std::list<QWidget *, std::allocator<QWidget *> > &)
END_CLASS

BEGIN_CLASS(QList<QObject *>)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(const QList<QObject *> &)
METHOD(operator=, QList<QObject *> &, const QList<QObject *> &)
METHOD(swap, void, QList<QObject *> &)
CONST_METHOD(operator==, bool, const QList<QObject *> &)
CONST_METHOD(operator!=, bool, const QList<QObject *> &)
CONST_METHOD(size, int)
METHOD(detach, void)
METHOD(detachShared, void)
CONST_METHOD(isDetached, bool)
METHOD(setSharable, void, bool)
CONST_METHOD(isSharedWith, bool, const QList<QObject *> &)
CONST_METHOD(isEmpty, bool)
METHOD(clear, void)
CONST_METHOD(at, QObject *const &, int)
CONST_METHOD(operator[], QObject *const &, int)
METHOD(operator[], QObject *&, int)
METHOD(reserve, void, int)
METHOD(append, void, QObject *const &)
METHOD(append, void, const QList<QObject *> &)
METHOD(prepend, void, QObject *const &)
METHOD(insert, void, int, QObject *const &)
METHOD(replace, void, int, QObject *const &)
METHOD(removeAt, void, int)
METHOD(removeAll, int, QObject *const &)
METHOD(removeOne, bool, QObject *const &)
METHOD(takeAt, QObject *, int)
METHOD(takeFirst, QObject *)
METHOD(takeLast, QObject *)
METHOD(move, void, int, int)
METHOD(swap, void, int, int)
CONST_METHOD(indexOf, int, QObject *const &, int)
CONST_METHOD(lastIndexOf, int, QObject *const &, int)
CONST_METHOD(contains, QBool, QObject *const &)
CONST_METHOD(count, int, QObject *const &)
METHOD(begin, QList<QObject *>::iterator)
CONST_METHOD(begin, QList<QObject *>::const_iterator)
CONST_METHOD(constBegin, QList<QObject *>::const_iterator)
METHOD(end, QList<QObject *>::iterator)
CONST_METHOD(end, QList<QObject *>::const_iterator)
CONST_METHOD(constEnd, QList<QObject *>::const_iterator)
METHOD(insert, QList<QObject *>::iterator, QList<QObject *>::iterator, QObject *const &)
METHOD(erase, QList<QObject *>::iterator, QList<QObject *>::iterator)
METHOD(erase, QList<QObject *>::iterator, QList<QObject *>::iterator, QList<QObject *>::iterator)
CONST_METHOD(count, int)
CONST_METHOD(length, int)
METHOD(first, QObject *&)
CONST_METHOD(first, QObject *const &)
METHOD(last, QObject *&)
CONST_METHOD(last, QObject *const &)
METHOD(removeFirst, void)
METHOD(removeLast, void)
CONST_METHOD(startsWith, bool, QObject *const &)
CONST_METHOD(endsWith, bool, QObject *const &)
CONST_METHOD(mid, QList<QObject *>, int, int)
CONST_METHOD(value, QObject *, int)
CONST_METHOD(value, QObject *, int, QObject *const &)
METHOD(push_back, void, QObject *const &)
METHOD(push_front, void, QObject *const &)
METHOD(front, QObject *&)
CONST_METHOD(front, QObject *const &)
METHOD(back, QObject *&)
CONST_METHOD(back, QObject *const &)
METHOD(pop_front, void)
METHOD(pop_back, void)
CONST_METHOD(empty, bool)
METHOD(operator+=, QList<QObject *> &, const QList<QObject *> &)
CONST_METHOD(operator+, QList<QObject *>, const QList<QObject *> &)
METHOD(operator+=, QList<QObject *> &, QObject *const &)
METHOD(operator<<, QList<QObject *> &, QObject *const &)
METHOD(operator<<, QList<QObject *> &, const QList<QObject *> &)
CONST_METHOD(toVector, QVector<QObject *>)
CONST_METHOD(toSet, QSet<QObject *>)
STATIC_METHOD(fromVector, QList<QObject *>, const QVector<QObject *> &)
STATIC_METHOD(fromSet, QList<QObject *>, const QSet<QObject *> &)
STATIC_METHOD(fromStdList, QList<QObject *>, const std::list<QObject *, std::allocator<QObject *> > &)
END_CLASS

BEGIN_CLASS(QList<QByteArray>)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(const QList<QByteArray> &)
METHOD(operator=, QList<QByteArray> &, const QList<QByteArray> &)
METHOD(swap, void, QList<QByteArray> &)
CONST_METHOD(operator==, bool, const QList<QByteArray> &)
CONST_METHOD(operator!=, bool, const QList<QByteArray> &)
CONST_METHOD(size, int)
METHOD(detach, void)
METHOD(detachShared, void)
CONST_METHOD(isDetached, bool)
METHOD(setSharable, void, bool)
CONST_METHOD(isSharedWith, bool, const QList<QByteArray> &)
CONST_METHOD(isEmpty, bool)
METHOD(clear, void)
CONST_METHOD(at, const QByteArray &, int)
CONST_METHOD(operator[], const QByteArray &, int)
METHOD(operator[], QByteArray &, int)
METHOD(reserve, void, int)
METHOD(append, void, const QByteArray &)
METHOD(append, void, const QList<QByteArray> &)
METHOD(prepend, void, const QByteArray &)
METHOD(insert, void, int, const QByteArray &)
METHOD(replace, void, int, const QByteArray &)
METHOD(removeAt, void, int)
METHOD(removeAll, int, const QByteArray &)
METHOD(removeOne, bool, const QByteArray &)
METHOD(takeAt, QByteArray, int)
METHOD(takeFirst, QByteArray)
METHOD(takeLast, QByteArray)
METHOD(move, void, int, int)
METHOD(swap, void, int, int)
CONST_METHOD(indexOf, int, const QByteArray &, int)
CONST_METHOD(lastIndexOf, int, const QByteArray &, int)
CONST_METHOD(contains, QBool, const QByteArray &)
CONST_METHOD(count, int, const QByteArray &)
METHOD(begin, QList<QByteArray>::iterator)
CONST_METHOD(begin, QList<QByteArray>::const_iterator)
CONST_METHOD(constBegin, QList<QByteArray>::const_iterator)
METHOD(end, QList<QByteArray>::iterator)
CONST_METHOD(end, QList<QByteArray>::const_iterator)
CONST_METHOD(constEnd, QList<QByteArray>::const_iterator)
METHOD(insert, QList<QByteArray>::iterator, QList<QByteArray>::iterator, const QByteArray &)
METHOD(erase, QList<QByteArray>::iterator, QList<QByteArray>::iterator)
METHOD(erase, QList<QByteArray>::iterator, QList<QByteArray>::iterator, QList<QByteArray>::iterator)
CONST_METHOD(count, int)
CONST_METHOD(length, int)
METHOD(first, QByteArray &)
CONST_METHOD(first, const QByteArray &)
METHOD(last, QByteArray &)
CONST_METHOD(last, const QByteArray &)
METHOD(removeFirst, void)
METHOD(removeLast, void)
CONST_METHOD(startsWith, bool, const QByteArray &)
CONST_METHOD(endsWith, bool, const QByteArray &)
CONST_METHOD(mid, QList<QByteArray>, int, int)
CONST_METHOD(value, QByteArray, int)
CONST_METHOD(value, QByteArray, int, const QByteArray &)
METHOD(push_back, void, const QByteArray &)
METHOD(push_front, void, const QByteArray &)
METHOD(front, QByteArray &)
CONST_METHOD(front, const QByteArray &)
METHOD(back, QByteArray &)
CONST_METHOD(back, const QByteArray &)
METHOD(pop_front, void)
METHOD(pop_back, void)
CONST_METHOD(empty, bool)
METHOD(operator+=, QList<QByteArray> &, const QList<QByteArray> &)
CONST_METHOD(operator+, QList<QByteArray>, const QList<QByteArray> &)
METHOD(operator+=, QList<QByteArray> &, const QByteArray &)
METHOD(operator<<, QList<QByteArray> &, const QByteArray &)
METHOD(operator<<, QList<QByteArray> &, const QList<QByteArray> &)
CONST_METHOD(toVector, QVector<QByteArray>)
CONST_METHOD(toSet, QSet<QByteArray>)
STATIC_METHOD(fromVector, QList<QByteArray>, const QVector<QByteArray> &)
STATIC_METHOD(fromSet, QList<QByteArray>, const QSet<QByteArray> &)
STATIC_METHOD(fromStdList, QList<QByteArray>, const std::list<QByteArray, std::allocator<QByteArray> > &)
END_CLASS

BEGIN_CLASS(QApplication)
SUPER_CLASS(QCoreApplication)
STATIC_METHOD(tr, QString, const char *, const char *)
STATIC_METHOD(trUtf8, QString, const char *, const char *)
STATIC_METHOD(tr, QString, const char *, const char *, int)
STATIC_METHOD(trUtf8, QString, const char *, const char *, int)
CONSTRUCTOR(int &, char **, int)
CONSTRUCTOR(int &, char **, bool, int)
CONSTRUCTOR(int &, char **, QApplication::Type, int)
CONSTRUCTOR(_XDisplay *, unsigned long, unsigned long, int)
CONSTRUCTOR(_XDisplay *, int &, char **, unsigned long, unsigned long, int)
STATIC_METHOD(type, QApplication::Type)
STATIC_METHOD(style, QStyle *)
STATIC_METHOD(setStyle, void, QStyle *)
STATIC_METHOD(setStyle, QStyle *, const QString &)
STATIC_METHOD(colorSpec, int)
STATIC_METHOD(setColorSpec, void, int)
STATIC_METHOD(setGraphicsSystem, void, const QString &)
STATIC_METHOD(overrideCursor, QCursor *)
STATIC_METHOD(setOverrideCursor, void, const QCursor &)
STATIC_METHOD(changeOverrideCursor, void, const QCursor &)
STATIC_METHOD(restoreOverrideCursor, void)
STATIC_METHOD(setPalette, void, const QPalette &, const char *)
STATIC_METHOD(setFont, void, const QFont &, const char *)
STATIC_METHOD(setWindowIcon, void, const QIcon &)
STATIC_METHOD(allWidgets, QList<QWidget *>)
STATIC_METHOD(topLevelWidgets, QList<QWidget *>)
STATIC_METHOD(desktop, QDesktopWidget *)
STATIC_METHOD(activePopupWidget, QWidget *)
STATIC_METHOD(activeModalWidget, QWidget *)
STATIC_METHOD(clipboard, QClipboard *)
STATIC_METHOD(focusWidget, QWidget *)
STATIC_METHOD(activeWindow, QWidget *)
STATIC_METHOD(setActiveWindow, void, QWidget *)
STATIC_METHOD(widgetAt, QWidget *, const QPoint &)
STATIC_METHOD(widgetAt, QWidget *, int, int)
STATIC_METHOD(topLevelAt, QWidget *, const QPoint &)
STATIC_METHOD(topLevelAt, QWidget *, int, int)
STATIC_METHOD(syncX, void)
STATIC_METHOD(beep, void)
STATIC_METHOD(alert, void, QWidget *, int)
STATIC_METHOD(keyboardModifiers, QFlags<Qt::KeyboardModifier>)
STATIC_METHOD(queryKeyboardModifiers, QFlags<Qt::KeyboardModifier>)
STATIC_METHOD(mouseButtons, QFlags<Qt::MouseButton>)
STATIC_METHOD(setDesktopSettingsAware, void, bool)
STATIC_METHOD(desktopSettingsAware, bool)
STATIC_METHOD(setCursorFlashTime, void, int)
STATIC_METHOD(cursorFlashTime, int)
STATIC_METHOD(setDoubleClickInterval, void, int)
STATIC_METHOD(doubleClickInterval, int)
STATIC_METHOD(setKeyboardInputInterval, void, int)
STATIC_METHOD(keyboardInputInterval, int)
STATIC_METHOD(setWheelScrollLines, void, int)
STATIC_METHOD(wheelScrollLines, int)
STATIC_METHOD(setGlobalStrut, void, const QSize &)
STATIC_METHOD(globalStrut, QSize)
STATIC_METHOD(setStartDragTime, void, int)
STATIC_METHOD(startDragTime, int)
STATIC_METHOD(setStartDragDistance, void, int)
STATIC_METHOD(startDragDistance, int)
STATIC_METHOD(setLayoutDirection, void, Qt::LayoutDirection)
STATIC_METHOD(layoutDirection, Qt::LayoutDirection)
STATIC_METHOD(isRightToLeft, bool)
STATIC_METHOD(isLeftToRight, bool)
STATIC_METHOD(isEffectEnabled, bool, Qt::UIEffect)
STATIC_METHOD(setEffectEnabled, void, Qt::UIEffect, bool)
METHOD(x11EventFilter, bool, _XEvent *)
METHOD(x11ClientMessage, int, QWidget *, _XEvent *, bool)
METHOD(x11ProcessEvent, int, _XEvent *)
CONST_METHOD(isSessionRestored, bool)
CONST_METHOD(sessionId, QString)
CONST_METHOD(sessionKey, QString)
METHOD(commitData, void, QSessionManager &)
METHOD(saveState, void, QSessionManager &)
METHOD(setInputContext, void, QInputContext *)
CONST_METHOD(inputContext, QInputContext *)
STATIC_METHOD(keyboardInputDirection, Qt::LayoutDirection)
STATIC_METHOD(exec, int)
STATIC_METHOD(setQuitOnLastWindowClosed, void, bool)
STATIC_METHOD(quitOnLastWindowClosed, bool)
CONST_METHOD(styleSheet, QString)
METHOD(setStyleSheet, void, const QString &)
METHOD(setAutoSipEnabled, void, const bool)
CONST_METHOD(autoSipEnabled, bool)
STATIC_METHOD(closeAllWindows, void)
STATIC_METHOD(aboutQt, void)
END_CLASS

BEGIN_CLASS(QList<void *>::const_iterator)
ATTRIBUTE(i, QList<void *>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<void *>::Node *)
CONSTRUCTOR(const QList<void *>::const_iterator &)
CONSTRUCTOR(const QList<void *>::iterator &)
CONST_METHOD(operator*, void *const &)
CONST_METHOD(operator->, void *const *)
CONST_METHOD(operator[], void *const &, int)
CONST_METHOD(operator==, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<void *>::const_iterator &)
METHOD(operator++, QList<void *>::const_iterator &)
METHOD(operator++, QList<void *>::const_iterator, int)
METHOD(operator--, QList<void *>::const_iterator &)
METHOD(operator--, QList<void *>::const_iterator, int)
METHOD(operator+=, QList<void *>::const_iterator &, int)
METHOD(operator-=, QList<void *>::const_iterator &, int)
CONST_METHOD(operator+, QList<void *>::const_iterator, int)
CONST_METHOD(operator-, QList<void *>::const_iterator, int)
CONST_METHOD(operator-, int, QList<void *>::const_iterator)
END_CLASS

BEGIN_CLASS(QList<void *>::iterator)
ATTRIBUTE(i, QList<void *>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<void *>::Node *)
CONSTRUCTOR(const QList<void *>::iterator &)
CONST_METHOD(operator*, void *&)
CONST_METHOD(operator->, void **)
CONST_METHOD(operator[], void *&, int)
CONST_METHOD(operator==, bool, const QList<void *>::iterator &)
CONST_METHOD(operator!=, bool, const QList<void *>::iterator &)
CONST_METHOD(operator<, bool, const QList<void *>::iterator &)
CONST_METHOD(operator<=, bool, const QList<void *>::iterator &)
CONST_METHOD(operator>, bool, const QList<void *>::iterator &)
CONST_METHOD(operator>=, bool, const QList<void *>::iterator &)
CONST_METHOD(operator==, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<void *>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<void *>::const_iterator &)
METHOD(operator++, QList<void *>::iterator &)
METHOD(operator++, QList<void *>::iterator, int)
METHOD(operator--, QList<void *>::iterator &)
METHOD(operator--, QList<void *>::iterator, int)
METHOD(operator+=, QList<void *>::iterator &, int)
METHOD(operator-=, QList<void *>::iterator &, int)
CONST_METHOD(operator+, QList<void *>::iterator, int)
CONST_METHOD(operator-, QList<void *>::iterator, int)
CONST_METHOD(operator-, int, QList<void *>::iterator)
END_CLASS

BEGIN_CLASS(QList<QWidget *>::const_iterator)
ATTRIBUTE(i, QList<QWidget *>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<QWidget *>::Node *)
CONSTRUCTOR(const QList<QWidget *>::const_iterator &)
CONSTRUCTOR(const QList<QWidget *>::iterator &)
CONST_METHOD(operator*, QWidget *const &)
CONST_METHOD(operator->, QWidget *const *)
CONST_METHOD(operator[], QWidget *const &, int)
CONST_METHOD(operator==, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<QWidget *>::const_iterator &)
METHOD(operator++, QList<QWidget *>::const_iterator &)
METHOD(operator++, QList<QWidget *>::const_iterator, int)
METHOD(operator--, QList<QWidget *>::const_iterator &)
METHOD(operator--, QList<QWidget *>::const_iterator, int)
METHOD(operator+=, QList<QWidget *>::const_iterator &, int)
METHOD(operator-=, QList<QWidget *>::const_iterator &, int)
CONST_METHOD(operator+, QList<QWidget *>::const_iterator, int)
CONST_METHOD(operator-, QList<QWidget *>::const_iterator, int)
CONST_METHOD(operator-, int, QList<QWidget *>::const_iterator)
END_CLASS

BEGIN_CLASS(QList<QWidget *>::iterator)
ATTRIBUTE(i, QList<QWidget *>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<QWidget *>::Node *)
CONSTRUCTOR(const QList<QWidget *>::iterator &)
CONST_METHOD(operator*, QWidget *&)
CONST_METHOD(operator->, QWidget **)
CONST_METHOD(operator[], QWidget *&, int)
CONST_METHOD(operator==, bool, const QList<QWidget *>::iterator &)
CONST_METHOD(operator!=, bool, const QList<QWidget *>::iterator &)
CONST_METHOD(operator<, bool, const QList<QWidget *>::iterator &)
CONST_METHOD(operator<=, bool, const QList<QWidget *>::iterator &)
CONST_METHOD(operator>, bool, const QList<QWidget *>::iterator &)
CONST_METHOD(operator>=, bool, const QList<QWidget *>::iterator &)
CONST_METHOD(operator==, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<QWidget *>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<QWidget *>::const_iterator &)
METHOD(operator++, QList<QWidget *>::iterator &)
METHOD(operator++, QList<QWidget *>::iterator, int)
METHOD(operator--, QList<QWidget *>::iterator &)
METHOD(operator--, QList<QWidget *>::iterator, int)
METHOD(operator+=, QList<QWidget *>::iterator &, int)
METHOD(operator-=, QList<QWidget *>::iterator &, int)
CONST_METHOD(operator+, QList<QWidget *>::iterator, int)
CONST_METHOD(operator-, QList<QWidget *>::iterator, int)
CONST_METHOD(operator-, int, QList<QWidget *>::iterator)
END_CLASS

BEGIN_CLASS(QList<QObject *>::const_iterator)
ATTRIBUTE(i, QList<QObject *>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<QObject *>::Node *)
CONSTRUCTOR(const QList<QObject *>::const_iterator &)
CONSTRUCTOR(const QList<QObject *>::iterator &)
CONST_METHOD(operator*, QObject *const &)
CONST_METHOD(operator->, QObject *const *)
CONST_METHOD(operator[], QObject *const &, int)
CONST_METHOD(operator==, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<QObject *>::const_iterator &)
METHOD(operator++, QList<QObject *>::const_iterator &)
METHOD(operator++, QList<QObject *>::const_iterator, int)
METHOD(operator--, QList<QObject *>::const_iterator &)
METHOD(operator--, QList<QObject *>::const_iterator, int)
METHOD(operator+=, QList<QObject *>::const_iterator &, int)
METHOD(operator-=, QList<QObject *>::const_iterator &, int)
CONST_METHOD(operator+, QList<QObject *>::const_iterator, int)
CONST_METHOD(operator-, QList<QObject *>::const_iterator, int)
CONST_METHOD(operator-, int, QList<QObject *>::const_iterator)
END_CLASS

BEGIN_CLASS(QList<QObject *>::iterator)
ATTRIBUTE(i, QList<QObject *>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<QObject *>::Node *)
CONSTRUCTOR(const QList<QObject *>::iterator &)
CONST_METHOD(operator*, QObject *&)
CONST_METHOD(operator->, QObject **)
CONST_METHOD(operator[], QObject *&, int)
CONST_METHOD(operator==, bool, const QList<QObject *>::iterator &)
CONST_METHOD(operator!=, bool, const QList<QObject *>::iterator &)
CONST_METHOD(operator<, bool, const QList<QObject *>::iterator &)
CONST_METHOD(operator<=, bool, const QList<QObject *>::iterator &)
CONST_METHOD(operator>, bool, const QList<QObject *>::iterator &)
CONST_METHOD(operator>=, bool, const QList<QObject *>::iterator &)
CONST_METHOD(operator==, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<QObject *>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<QObject *>::const_iterator &)
METHOD(operator++, QList<QObject *>::iterator &)
METHOD(operator++, QList<QObject *>::iterator, int)
METHOD(operator--, QList<QObject *>::iterator &)
METHOD(operator--, QList<QObject *>::iterator, int)
METHOD(operator+=, QList<QObject *>::iterator &, int)
METHOD(operator-=, QList<QObject *>::iterator &, int)
CONST_METHOD(operator+, QList<QObject *>::iterator, int)
CONST_METHOD(operator-, QList<QObject *>::iterator, int)
CONST_METHOD(operator-, int, QList<QObject *>::iterator)
END_CLASS

BEGIN_CLASS(QList<QByteArray>::const_iterator)
ATTRIBUTE(i, QList<QByteArray>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<QByteArray>::Node *)
CONSTRUCTOR(const QList<QByteArray>::const_iterator &)
CONSTRUCTOR(const QList<QByteArray>::iterator &)
CONST_METHOD(operator*, const QByteArray &)
CONST_METHOD(operator->, const QByteArray *)
CONST_METHOD(operator[], const QByteArray &, int)
CONST_METHOD(operator==, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<QByteArray>::const_iterator &)
METHOD(operator++, QList<QByteArray>::const_iterator &)
METHOD(operator++, QList<QByteArray>::const_iterator, int)
METHOD(operator--, QList<QByteArray>::const_iterator &)
METHOD(operator--, QList<QByteArray>::const_iterator, int)
METHOD(operator+=, QList<QByteArray>::const_iterator &, int)
METHOD(operator-=, QList<QByteArray>::const_iterator &, int)
CONST_METHOD(operator+, QList<QByteArray>::const_iterator, int)
CONST_METHOD(operator-, QList<QByteArray>::const_iterator, int)
CONST_METHOD(operator-, int, QList<QByteArray>::const_iterator)
END_CLASS

BEGIN_CLASS(QList<QByteArray>::iterator)
ATTRIBUTE(i, QList<QByteArray>::Node *)
DEFAULT_CONSTRUCTOR()
CONSTRUCTOR(QList<QByteArray>::Node *)
CONSTRUCTOR(const QList<QByteArray>::iterator &)
CONST_METHOD(operator*, QByteArray &)
CONST_METHOD(operator->, QByteArray *)
CONST_METHOD(operator[], QByteArray &, int)
CONST_METHOD(operator==, bool, const QList<QByteArray>::iterator &)
CONST_METHOD(operator!=, bool, const QList<QByteArray>::iterator &)
CONST_METHOD(operator<, bool, const QList<QByteArray>::iterator &)
CONST_METHOD(operator<=, bool, const QList<QByteArray>::iterator &)
CONST_METHOD(operator>, bool, const QList<QByteArray>::iterator &)
CONST_METHOD(operator>=, bool, const QList<QByteArray>::iterator &)
CONST_METHOD(operator==, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator!=, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator<, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator<=, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator>, bool, const QList<QByteArray>::const_iterator &)
CONST_METHOD(operator>=, bool, const QList<QByteArray>::const_iterator &)
METHOD(operator++, QList<QByteArray>::iterator &)
METHOD(operator++, QList<QByteArray>::iterator, int)
METHOD(operator--, QList<QByteArray>::iterator &)
METHOD(operator--, QList<QByteArray>::iterator, int)
METHOD(operator+=, QList<QByteArray>::iterator &, int)
METHOD(operator-=, QList<QByteArray>::iterator &, int)
CONST_METHOD(operator+, QList<QByteArray>::iterator, int)
CONST_METHOD(operator-, QList<QByteArray>::iterator, int)
CONST_METHOD(operator-, int, QList<QByteArray>::iterator)
END_CLASS


